<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees [
    <!ELEMENT employees (employee+)>
    <!ELEMENT employee (empID, name, department, designation, email, salary)>
    <!ELEMENT empID (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT department (#PCDATA)>
    <!ELEMENT designation (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT salary (#PCDATA)>
]>
<employees>
    <employee>
        <empID>101</empID>
        <name>Rahul Sharma</name>
        <department>IT</department>
        <designation>Software Engineer</designation>
        <email>rahul.sharma@example.com</email>
        <salary>60000</salary>
    </employee>
    <employee>
        <empID>102</empID>
        <name>Pooja Patel</name>
        <department>HR</department>
        <designation>HR Manager</designation>
        <email>pooja.patel@example.com</email>
        <salary>75000</salary>
    </employee>
</employees>
