=== Yash12-cloud/Web-Tech_Practical/Practical 5/employee.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (empID, name, department, designation, email, salary)>
<!ELEMENT empID (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== Yash12-cloud/Web-Tech_Practical/Practical 5/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<employees>
    <employee>
        <empID>201</empID>
        <name>Amit Verma</name>
        <department>Finance</department>
        <designation>Accountant</designation>
        <email>amit.verma@example.com</email>
        <salary>50000</salary>
    </employee>
    <employee>
        <empID>202</empID>
        <name>Neha Gupta</name>
        <department>Marketing</department>
        <designation>Marketing Executive</designation>
        <email>neha.gupta@example.com</email>
        <salary>55000</salary>
    </employee>
</employees>
